name: Git Copier

on:

  [push, pull_request, workflow_dispatch]

jobs:

  clone:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Clone
        run: git clone https://github.com/${{ github.repository }}.git
      - name: Upload clone

        uses: actions/upload-artifact@v2

        with:

          name: Cloned Git repository

          path: ${{ github.repository }}.git
