name: Git Copier

on:

  [push, pull_request, public, workflow_dispatch]

jobs:

  clone:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Clone
        id: gitcloning
      
        run: git clone https://github.com/${{ github.repository }}.git
      - name: Upload clone
        if: ${{ success(gitcloning) }}
        uses: actions/upload-artifact@v2

        with:

          name: Cloned Git repository

          path: ${{ github.repository_name }}.git
